# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build and Analyse
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
      run: |
        mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=meyy-innerpeace -Dsonar.projectKey=maven-sonar 
        STATUS=`curl -s https://sonarcloud.io/api/qualitygates/project_status?projectKey=maven-sonar | jq ".projectStatus.status"`
        if [ "$STATUS" == "\"ERROR\"" ]; then    echo "Sonar Quality Gate Failed, Please check the Sonar log" && exit 1 ; fi
      # run: mvn clean install
      
